### ISSUE TITLE
Rename to AnVIL_Book_Template ?

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/AnVIL_Template#43]
parallels OTTR_Template

I originally created this repo to mess around with the AnVIL style-set without causing problems in the Getting Started repo, hence the "style" name, but we're aiming for something more ambitious now :)

**Comment by avahoffman** [comment]
What about just AnVIL_Template?

**Comment by KatherineCox** [comment]
Thoughts:

- I like that AnVIL_Template better matches OTTR_Template
- I like that it's shorter.
- How likely is it that jhudsl would be doing other AnVIL stuff (i.e. unrelated to making training material) for which "AnVIL_Template" would be ambiguous?  I like that AnVIL_Book_Template is pretty obviously the thing you use to make AnVIL books.

Conclusion: I'm good with AnVIL_Template 👍 .  I don't think people are actually going to be confused about what this is if we drop "Book".

**Comment by avahoffman** [comment]
Sounds good. I can change the name over tonight (let's get any pending PRs in first)

**Comment by KatherineCox** [comment]
Ok.  I haven't tried actually running anything from #48, I was just starting to look at how syncing works, so, it may or may not be functional.  But I also don't think it will cause any problems if we just merge it as is.  The workflow is triggered by releases (or manually), so it shouldn't run.

**Comment by avahoffman** [comment]
Done! Shouldn't actually interfere with the PRs
