### ISSUE TITLE
GHA not able to commit AnVIL Repos file

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/AnVIL_Template#97]
The custom workflow creates a file, AnVIL_repos.tsv, that allows a library of AnVIL content to be rendered on the index page. In short, it calls the github API for repos that match AnVIL or GDSCN naming convention, to look like this:

![image](https://user-images.githubusercontent.com/15618412/159925183-6222db33-31f7-43d1-96e1-06d9b79491b0.png)

This works as expected when submitting a pull request - the API is queried and an updated table is created. This is where this happens:

https://github.com/jhudsl/AnVIL_Template/blob/68644cba827e01200814afe9dfcfc3d7871cafcb/.github/workflows/custom-workflow.yml#L76

But it doesn't work when rendering on main. 

https://github.com/jhudsl/AnVIL_Template/blob/68644cba827e01200814afe9dfcfc3d7871cafcb/.github/workflows/custom-workflow.yml#L65

**This problem is solved when main is not protected (repo settings).** Otherwise, when the AnVIL_repos.tsv file is changed and committed, action produces an error that looks like the following:

```
Run git checkout main
Switched to a new branch 'main'
M	resources/AnVIL_repos.tsv
Branch 'main' set up to track remote branch 'main' from 'origin'.
[main bf22805] Add AnVIL repos file
 1 file changed, 4 insertions(+), 1 deletion(-)
Already up to date.
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/jhudsl/AnVIL_Template
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/jhudsl/AnVIL_Template'
No changes to push
```

**Comment by avahoffman** [comment]
@cansavvy if you branch off of main, and run render-all workflow, you should be able to reproduce this error.

**Comment by cansavvy** [comment]
This post: https://github.community/t/reusable-workflows-secrets-and-environments/203695/17 appears to suggest that secrets need to be passed explicitly to reusable workflows which seems like an unexpected thing that github actions needs. The documentation doesn't seem very clear about this from what I've looked at.
